FROM ubuntu:latest

RUN mkdir sample_dir    # <- Create a directory in the / directory
RUN cd sample_dir       # <- change directory, However, it is valid only for the RUN instruction
RUN touch sample_file   # <- Create a file in the / directory

