version: '3'

services:
  web:
    image: datascientistus/ds-python-env
    ports:
      - '8888:8888'
    volumes:
      - './work:/work'
    tty: true
    stdin_open: true
    environment:
      - 'name:my-env'

