---

- name: Install gunicorn
  apt:
    name: gunicorn

- name: Python Framework
  easy_install:
    name: "{{ item }}"
  with_items:
    - itsdangerous
    - flask

- name: Create new directory
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: 0755

- name: Drop app soure
  copy:
    src: hello.py
    dest: "{{ app_dir }}/hello.py"

- name: Install supervisor
  apt:
    name: supervisor

- name: Drop supervisord conf
  template:
    src: app.conf.j2
    dest: /etc/supervisor/conf.d/app.conf

- name: Start supervisor
  service:
    name: supervisor
    enabled: yes
    state: restarted

